/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comp3111G15;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Before;
import org.junit.Test;

public class LibraryTest {
	
	ArrayList<Student> student_data;
	Student student1;
	Student student2;
	Student student3;
	
	@Before
	public void setUp() throws Exception {
		student_data = new ArrayList<Student>();
		student1 = new Student("20004488", "SAFFRON, Corgipoo", "CorgipooSAF@connect.ust.hk", 
				"26", "80", "0", "1", "0", "");
		student2 = new Student("20023331", "HYSSOP, Chamois", "ChamoisHYS@connect.ust.hk", 
				"27", "85", "0", "1", "1", "");
		student3 = new Student("20067232", "CHRYSANTHEMUM, Abelisaurus", "AbelisaurusCHR@connect.ust.hk", 
				"57", "60", "1", "0", "1", "");
		student_data.add(student1);
		student_data.add(student2);
		student_data.add(student3);

	}
	
	@Test
	public void isStudentNameEqual() {
		assertEquals("SAFFRON, Corgipoo", student1.getName());
	}
	
	@Test
	public void isStudentIDEqual() {
		assertEquals("20004488", student1.getID());
	}
	
	@Test
	public void isStudentEmailEqual() {
		assertEquals("CorgipooSAF@connect.ust.hk", student1.getEmail());
	}
	
	@Test
	public void isStudentK1Equal() {
		assertEquals(26, student1.getK1Energy());
	}
	
	@Test
	public void isStudentK2Equal() {
		assertEquals(80, student1.getK2Energy());
	}
	
	@Test
	public void isStudentK1Larger() {
		assertEquals(-1, student2.compareTo(student1));
	}
	
	@Test
	public void isStudentK1Smaller() {
		assertEquals(1, student2.compareTo(student3));
	}
	
	@Test
	public void isStudentK1CompareEqual() {
		assertEquals(0, student2.compareTo(student2));
	}
	
	@Test
	public void isStudentK3Tick1ReturnFalse() {
		assertFalse(student1.getK3Tick1());
	}
	
	@Test
	public void isStudentK3Tick2ReturnTrue() {
		assertTrue(student1.getK3Tick2());
	}

	@Test
	public void isK1MMMEqual() {
		assertEquals("(36.7, 26, 57)", InputManager.get_student_k1_mmm(student_data));
	}

	@Test
	public void isK2MMMEqual() {
		assertEquals("(75.0, 60, 85)", InputManager.get_student_k2_mmm(student_data));
	}
	
	@Test
	public void isK3_tick1Equal() {
		String t = InputManager.get_k3_ticks(student_data)[0];
		assertEquals("1", t);
	}
	
	@Test
	public void isK3_tick2Equal() {
		String t = InputManager.get_k3_ticks(student_data)[1];
		assertEquals("2", t);
	}
	
	@Test
	public void isMyPrefEqual() {
		String t = InputManager.get_k3_ticks(student_data)[2];
		assertEquals("2", t);
	}
}