/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comp3111G15;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library_sample classUnderTest = new Library_sample();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
